# 37 
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Kecil), ("KecepatanAngin", LowRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", YesTrans)])
# 38
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Kecil), ("KecepatanAngin", LowRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", YesTrans)])
# 39
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Kecil), ("KecepatanAngin", LowRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 40
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Kecil), ("KecepatanAngin", HighRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", NoTrans)])
# 41
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Kecil), ("KecepatanAngin", HighRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", NoTrans)])
# 42
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Kecil), ("KecepatanAngin", HighRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 43
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Besar), ("KecepatanAngin", LowRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", NoTrans)])
# 44
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Besar), ("KecepatanAngin", LowRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", NoTrans)])
# 45
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Besar), ("KecepatanAngin", LowRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 46
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Besar), ("KecepatanAngin", HighRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", NoTrans)])
# 47 
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Besar), ("KecepatanAngin", HighRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", NoTrans)])
# 48
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", OT), ("BedaKecepatan", Besar), ("KecepatanAngin", HighRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 49
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Kecil), ("KecepatanAngin", LowRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", NoTrans)])
# 50
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Kecil), ("KecepatanAngin", LowRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", NoTrans)])
# 51
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Kecil), ("KecepatanAngin", LowRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 52
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Kecil), ("KecepatanAngin", HighRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", NoTrans)])
# 53
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Kecil), ("KecepatanAngin", HighRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", NoTrans)])
# 54
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Kecil), ("KecepatanAngin", HighRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 55
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Besar), ("KecepatanAngin", LowRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", NoTrans)])
# 56
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Besar), ("KecepatanAngin", LowRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", NoTrans)])
# 57
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Besar), ("KecepatanAngin", LowRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 58
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Besar), ("KecepatanAngin", HighRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", NoTrans)])
# 59
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Besar), ("KecepatanAngin", HighRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", NoTrans)])
# 60
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", C), ("BedaKecepatan", Besar), ("KecepatanAngin", HighRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 61
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Kecil), ("KecepatanAngin", LowRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", YesTrans)])
# 62
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Kecil), ("KecepatanAngin", LowRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", YesTrans)])
# 63
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Kecil), ("KecepatanAngin", LowRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 64
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Kecil), ("KecepatanAngin", HighRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", NoTrans)])
# 65
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Kecil), ("KecepatanAngin", HighRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", NoTrans)])
# 66
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Kecil), ("KecepatanAngin", HighRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 67
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Besar), ("KecepatanAngin", LowRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", NoTrans)])
# 68
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Besar), ("KecepatanAngin", LowRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", NoTrans)])
# 69
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Besar), ("KecepatanAngin", LowRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])
# 70
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Besar), ("KecepatanAngin", HighRisk), ("CurahHujan", CR)], 
                  [("HasilKeputusan", NoTrans)])
# 71
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Besar), ("KecepatanAngin", HighRisk), ("CurahHujan", HS)], 
                  [("HasilKeputusan", NoTrans)])
# 72
myIT2FLS.add_rule([("Jarak", Jauh), ("BedaHeading", HO), ("BedaKecepatan", Besar), ("KecepatanAngin", HighRisk), ("CurahHujan", HL)], 
                  [("HasilKeputusan", NoTrans)])